name: release

on:
  schedule:
  - cron: '0 3 * * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-18.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check Coredns version
        run: |
          new_ver=$(curl https://github.com/coredns/coredns/releases/latest | grep -Po "v(\d+\.){2}\d+")
          echo ::set-env name=RELEASE_TAG::"$new_ver"

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - uses: actions/checkout@v2
      - name: Build latest coredns
        run: |
          go version
          ./build.sh release ${{ env.RELEASE_TAG }}

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=${{ env.RELEASE_TAG }}
          gh release delete $tag_name -y || true
          git push origin :$tag_name || true
          gh release create $tag_name -t "$tag_name" --target $GITHUB_SHA *.zip
